//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReflectionTask.ServiceNew {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNew.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataDictionaryOne", ReplyAction="http://tempuri.org/IService/GetDataDictionaryOneResponse")]
        System.Collections.Generic.Dictionary<string, int> GetDataDictionaryOne(string fileContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataDictionaryOne", ReplyAction="http://tempuri.org/IService/GetDataDictionaryOneResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetDataDictionaryOneAsync(string fileContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataDictionaryTwo", ReplyAction="http://tempuri.org/IService/GetDataDictionaryTwoResponse")]
        System.Collections.Generic.Dictionary<string, int> GetDataDictionaryTwo(string fileContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataDictionaryTwo", ReplyAction="http://tempuri.org/IService/GetDataDictionaryTwoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetDataDictionaryTwoAsync(string fileContent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ReflectionTask.ServiceNew.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ReflectionTask.ServiceNew.IService>, ReflectionTask.ServiceNew.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetDataDictionaryOne(string fileContent) {
            return base.Channel.GetDataDictionaryOne(fileContent);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetDataDictionaryOneAsync(string fileContent) {
            return base.Channel.GetDataDictionaryOneAsync(fileContent);
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetDataDictionaryTwo(string fileContent) {
            return base.Channel.GetDataDictionaryTwo(fileContent);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetDataDictionaryTwoAsync(string fileContent) {
            return base.Channel.GetDataDictionaryTwoAsync(fileContent);
        }
    }
}
